<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BRIDT-1420" ignored="1" name="Default test(failed)" tests="2" failures="1" timestamp="05 Dec 2017 11:30:55 GMT" time="0.047" errors="0">
  <testcase name="ClassOneTestTwo" time="0.016" classname="test.SampleTestClassOne">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at test.SampleTestClassOne.ClassOneTestTwo(SampleTestClassOne.java:14)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- ClassOneTestTwo -->
  <testcase name="ClassOneTestThree" time="0.002" classname="test.SampleTestClassOne"/>
  <testcase name="ClassOneTestOne" time="0.0" classname="test.SampleTestClassOne">
    <ignored/>
  </testcase> <!-- ClassOneTestOne -->
</testsuite> <!-- Default test(failed) -->
